---
include:
  - "app/**/*.rb"
  - "lib/**/*.rb"

exclude:
  - "app/assets/**"
  - spec/**/**
  - test/**/**
  - vendor/**/**
  - tmp/**/**
  - node_modules/**/**
  - coverage/**/**
  - public/**/**
  - ".vscode/**/**"
  - ".bundle/**/*"
  - ".git/**/*"

reporters:
  - rubocop
  - require_not_found

require: []
domains: []
plugins: []
max_files: 5000
